# Generated by Django 5.0.7 on 2024-10-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=150)),
                ('taskDescription', models.TextField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
